### ISSUE TITLE
decompression wrong for certain allowed image dimensions

### ISSUE THREAD

**Issue by okonomiyonda** [GammaUNC/GST#2]
Hey guys, I am trying to compress a 2432x1024 image which should be an allowed size, but the results look really wrong. The texture is extremely noisy and blocks seem to be shifted over from where they should be. However, if I pad the same texture out to 2048x2048 and fill the unused space with white (or black), the results are perfect. I'm not sure why the exact same texture padded out to a larger size would fix the issue, but it feels like a bug somewhere

Attached is a zip file with two directories. working_2048x2048 contains the original image padded to 2048x2048 and the GST decompressed compressed image. The broken_2432x1024 directory contains the original 2432x1024 file, a compressed .gst file, and a GST decompressed result

[working_and_broken.zip](https://github.com/GammaUNC/GST/files/1019591/working_and_broken.zip)

**Comment by Mokosha** [comment]
I'm having a hard time reproducing this. Can you see if you use a png and run it through the ['dxt_tester'](https://github.com/GammaUNC/GST/commit/e530f382727794885bb49c44992359e314acd2b3) tool if you get the same results?

**Comment by Mokosha** [comment]
These are the results I got using Visual Studio 2017, x64 Release, with an AMD 7870

Compressed and decoded as png:
![gst_bug_2_dxt](https://cloud.githubusercontent.com/assets/885364/26342363/b0b5aa3e-3f4c-11e7-91d3-c17d4b7fe671.png)

Original png:
![gst_bug_2](https://cloud.githubusercontent.com/assets/885364/26342364/b0bc977c-3f4c-11e7-91b6-5376375b6cad.png)

**Comment by okonomiyonda** [comment]
Sorry for the late update but I wanted to look into some stuff before getting back to you. It seems like OpenCL is silently failing to launch some kernels with error CL_INVALID_WORK_GROUP_SIZE. We are running afoul of the requirement where local workgroup size has to evenly divide global work size. In the case of my textures, the stage 2 launch of decode_indices is calculating a global work size of (128,1) and a local workgroup size of (9,1). I have fixed the workgroup calculations and the images look perfect now.
