### ISSUE TITLE
Google patent application for ANS in image and video compression

### ISSUE THREAD

**Issue by JarekDuda** [GammaUNC/GST#3]
Hi,
Great work with GST!
I am writing because December 2016 Google has filled a very broad patent application for using ANS in image and video compression - if granted, it might be seen as a legal risk for using GST.
I see you mention ANS in this repository [November 2015](https://github.com/GammaUNC/GST/commit/1dbe380836ae9d64cddd666ecb9759dc62ece9e8) for image compression - I though it would be in your interest to document this situation in "Third-Party Preissuance Submission" to prevent granting this dangerous patent?
Claims and other details: https://encode.ru/threads/2648-Published-rANS-patent-by-Storeleap/page3
Best,
Jarek Duda

**Comment by Mokosha** [comment]
Thanks for the heads up. I'll keep an eye on it.
